[package]
name = "kdeconnectjb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
kdeconnect = { version = "0.1.0", path = "../kdeconnect" }
tokio = { version = "1.37.0", features = ["full"] }

[build-dependencies]
cbindgen = "0.26.0"
